# Generated by Django 4.1.7 on 2023-04-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='start_time',
            new_name='startTime',
        ),
    ]
