# Generated by Django 4.1.7 on 2023-04-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_batch_remove_student_batch_id_lecture_batch_students'),
        ('attendance', '0003_remove_attendance_sap_id_remove_batch_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='batch_name',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lec_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lecture'),
        ),
        migrations.DeleteModel(
            name='batch',
        ),
        migrations.DeleteModel(
            name='lecture',
        ),
    ]
