# Generated by Django 4.1 on 2023-04-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_end_time_lecture_endtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectteacher',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='subjectteacher',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='BatchStudent',
        ),
        migrations.DeleteModel(
            name='SubjectTeacher',
        ),
    ]
