# Generated by Django 4.1 on 2023-05-04 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_middle_name'),
        ('attendance', '0005_alter_batch_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_teacher_assigned', to='attendance.batch')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_batch', to='accounts.teacher')),
            ],
        ),
    ]
