# Generated by Django 4.1.7 on 2023-05-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
        ('attendance', '0005_alter_batch_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='number_of_students',
            field=models.IntegerField(null=True),
        ),
    ]
