# Generated by Django 4.1 on 2023-05-04 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_batch_class_teacher_and_more'),
        ('attendance', '0006_teacherbatch'),
    ]

    operations = [
    ]
