# Generated by Django 4.1.7 on 2023-05-07 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_subjects'),
        ('attendance', '0007_merge_20230504_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Attendance_subject', to='accounts.subject'),
        ),
    ]
