# Generated by Django 4.1.7 on 2023-07-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_attendance_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='date_time',
        ),
    ]
