# Generated by Django 4.1.7 on 2023-08-15 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_teacher_subjects'),
        ('attendance', '0009_remove_attendance_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
