# Generated by Django 4.1.7 on 2023-03-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teachers_delete_batch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teachers',
            new_name='teacher',
        ),
    ]
