# Generated by Django 4.1.7 on 2023-03-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_teachers_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='sap_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='teacher_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='unique_id',
            new_name='sap_id',
        ),
    ]
