# Generated by Django 4.1 on 2023-03-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_sap_id_student_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='@gmail.com', help_text='Enter your email', max_length=254, unique=True),
        ),
    ]
