# Generated by Django 4.1.7 on 2023-04-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendance_sap_id_remove_batch_students_and_more'),
        ('accounts', '0010_user_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch_id',
            field=models.ManyToManyField(related_name='belongs_to', to='attendance.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='totalAttendance',
            field=models.IntegerField(default=0),
        ),
    ]
