# Generated by Django 4.1.7 on 2023-04-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_batch_id_student_totalattendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batch_name', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('number_of_students', models.IntegerField()),
                ('department', models.CharField(max_length=125)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='batch_id',
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('lec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(max_length=250)),
                ('batch_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.batch')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
    ]
