# Generated by Django 4.1.7 on 2023-04-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_batch_remove_student_batch_id_lecture_batch_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name',
        ),
    ]
