# Generated by Django 4.1.7 on 2023-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_subject_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='subject',
            name='name',
            field=models.CharField(default='CN', max_length=45),
        ),
    ]
