# Generated by Django 4.1.7 on 2023-04-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_teacher_name_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='batches',
            field=models.ManyToManyField(to='accounts.batch'),
        ),
        migrations.CreateModel(
            name='StudentBatchRlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='accounts.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='accounts.student')),
            ],
        ),
    ]
